-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 16:47:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escapegame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escapegame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escapegame` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `escapegame` ;

-- -----------------------------------------------------
-- Table `escapegame`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`equipe` (
  `idequipe` INT NOT NULL,
  `nom` VARCHAR(70) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idequipe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`mission` (
  `idmission` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idmission`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`missionEtat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`missionEtat` (
  `idetat` INT NOT NULL,
  `heuredebut` TIME NOT NULL,
  `heurefin` TIME NULL DEFAULT NULL,
  `idgame` INT NOT NULL,
  `idmission` INT NOT NULL,
  PRIMARY KEY (`idetat`),
  INDEX `fk_missionEtat_mission1_idx` (`idmission` ASC) VISIBLE,
  CONSTRAINT `fk_missionEtat_mission1`
    FOREIGN KEY (`idmission`)
    REFERENCES `escapegame`.`mission` (`idmission`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`scenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`scenario` (
  `idscenario` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `ordre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idscenario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`game` (
  `idgame` INT NOT NULL,
  `idmissionEtat` INT NOT NULL,
  `idscenario` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `idequipe` INT NOT NULL,
  PRIMARY KEY (`idgame`),
  INDEX `fk_game_scenario1_idx` (`idscenario` ASC) VISIBLE,
  INDEX `fk_game_missionEtat1_idx` (`idmissionEtat` ASC) VISIBLE,
  INDEX `fk_game_equipe1_idx` (`idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_game_equipe1`
    FOREIGN KEY (`idequipe`)
    REFERENCES `escapegame`.`equipe` (`idequipe`),
  CONSTRAINT `fk_game_missionEtat1`
    FOREIGN KEY (`idmissionEtat`)
    REFERENCES `escapegame`.`missionEtat` (`idetat`),
  CONSTRAINT `fk_game_scenario1`
    FOREIGN KEY (`idscenario`)
    REFERENCES `escapegame`.`scenario` (`idscenario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`salle` (
  `idsalle` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idsalle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`utilisateur` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `escapegame`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escapegame`.`reservation` (
  `idreservation` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `utilisateur` INT NOT NULL,
  `salle` INT NOT NULL,
  `equipe` INT NOT NULL,
  PRIMARY KEY (`idreservation`),
  INDEX `fk_reservation_utilisateur1_idx` (`utilisateur` ASC) VISIBLE,
  INDEX `fk_reservation_salle1_idx` (`salle` ASC) VISIBLE,
  INDEX `fk_reservation_equipe1_idx` (`equipe` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_salle1`
    FOREIGN KEY (`salle`)
    REFERENCES `escapegame`.`salle` (`idsalle`),
  CONSTRAINT `fk_reservation_utilisateur1`
    FOREIGN KEY (`utilisateur`)
    REFERENCES `escapegame`.`utilisateur` (`idUser`),
  CONSTRAINT `fk_reservation_equipe1`
    FOREIGN KEY (`equipe`)
    REFERENCES `escapegame`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
